### PR TITLE
Addition of spatialite tests

### PR DESCRIPTION
**Pull request by richardellison**
It is still a bit rough around the edges (there is very little error checking) but seems to work for the New York City data.

example:

```{r}
dl_bikedata(data_dir = "../citibikedata/")
importDataToSpatialite(list.files("../citibikedata/", ".csv", full.names = TRUE), "../citibikedata/nyc.sqlite")
```

```{r}
Unit: seconds
             expr      min      lq     mean   median       uq      max neval
 testspatialite() 22.60358 22.6496 23.06895 23.15073 23.37577 23.48403    10
```

### CODE REVIEW

**Comment by richardellison** [comment]
I suspect that the build is failing because Travis-CI needs the sqlite3 and spatialite dependencies which I don't think are automatically installed.

**Comment by richardellison** [comment]
Build passes now that I have added libspatialite and properly documented importDataToSpatialite().

**Comment by mpadge** [comment]
Thanks @richardellison - i'll have a play around with it and get back to you. Just FYI: `src/Makevars` is generated by `configure` and `src/Makevars.in`, because Codecov doesn't work properly with a hard-coded `src/Makevars`.

**Comment by richardellison** [comment]
I realised that configure creates src/Makevars. I forgot to delete it after building. Do you know if there is a way to remove it automatically after building the package. I tried adding a cleanup script but I think that is only run some of the time.

**Comment by mpadge** [comment]
[This commit](https://github.com/mpadge/bikedata/commit/a92bfc9c2fae30f67efb5f8d5c0fb655704ec9ba) fixed it, but 2 mysteries remain:
1. Removing the `exit 0` was somehow necessary to get it to work
2. It also needed a `chmod u+x`, but `R CMD build` seems not to recognise that. It builds properly nonetheless but is strange that exec permissions are not recognised by `build`

**Pull request merged**
